/*
 * generated by Xtext
 */
package com.pellcorp.mydsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.pellcorp.mydsl.ui.internal.MyDslActivator.getInstance().getInjector("com.pellcorp.mydsl.MyDsl");
	}
	
}
